version: "3.9"  
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: spreads
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5544:5432"  
  datafetcher:
    build:
      context: ./DataFetcher
    ports:
      - "5001:8080"
    depends_on:
      - rabbitmq
      - postgres

  spreadcalculator:
    build:
      context: ./SpreadCalculator
    ports:
      - "5002:8080"
    depends_on:
      - rabbitmq
      - postgres

volumes:
  pgdata:

